dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      port: 5432
      dbname: TransJak
      schema: datamart
      threads: 4
